### ISSUE TITLE
Define Fields of Interest

### ISSUE THREAD

**Issue by victorddiniz** [victorddiniz/VisAIDSBrazil#1]
Define which of the fields in the [TabNe softwaret](http://www2.aids.gov.br/cgi/tabcgi.exe?tabnet/br.def) will be extracted.  

## Extractions of interest:
All the datasets extracted are for the years between 1982 and 2016.
* Year of diagnosis
* State of residence
* Age group (13)
* Gender group
* Ethnicity group
* Schooling degree
* Hierarchical exposition category

### Summary Extraction
It has the data for each possible value of a field of interest for a given year.
Dataset link: https://drive.google.com/drive/folders/0B7hPEQ9OXZiDUGxEejFIV19XdDA?usp=sharing

### Detail Extraction
It has the data for each possible combination of values of all fields of interest for a given year.
Dataset link: Not done.

![tg](https://cloud.githubusercontent.com/assets/6431117/24326692/ac44cada-1192-11e7-8fed-ca130932325f.png)

**Comment by victorddiniz** [comment]
@nivan can you have a look on this fields and check if you think something else might be interesting? The ideia is to download each of this relations also relating to time.

**Comment by nivan** [comment]
I think all of them are interesting. 
The only problem I see with these is that we won1t be able to link for example geography and gender, will we? I know this is a limitation of this system they put online, but is something to keep in mind so in the future we might try to get a more detailed dataset. However, the relations above are more than enough for now.

**Comment by victorddiniz** [comment]
That is right, it is because of system's limitation, but in the list above there is a entry to download UF X Sex, which is what you meant right? And to check this relationship's evolution I'll download for each relationship the data from years of 1992 to 2016. So I think this specific relation we are set. Although some complicated ones like Schooling X Sex X Ethnicity across the years are not possible to take from the system and have to be inferred from merging datasets.
