### ISSUE TITLE
Vision: For a given year, heat map of AIDS in Brazil

### ISSUE THREAD

**Issue by victorddiniz** [victorddiniz/VisAIDSBrazil#4]
Simple vision to display a heat map of AIDS for each state in Brazil.

- [x] Heuristic for scale. Just use scale for [minimum, maximum] won't work as São Paulo is always bigger than everyone, but is also much more populated.

**Comment by visualizacao-ufpe** [comment]
Oi Victor,

Seria legal usar o github pages para criar links que possam ser rodados diretamente online. Quando vocë for criar os demos tente fazer isso.

**Comment by victorddiniz** [comment]
Heurística para escalar de cor: Usar a média da porcentagens de população infectada como forma de definir a cor do médio e +1.5 * (desvio padrão) para a cor máxima e -1.5 * (desvio padrão) para definir a cor mínima.

**Comment by victorddiniz** [comment]
Nova heurística: utilizar número de habitantes infectados por uma dada parcela da população. Deste modo segue modelo utilizado em outras fontes e permite uma visualização mais rápida.
